services:
  elasticsearch:
    image: elasticsearch:8.18.3
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.license.self_generated.type=trial
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.18.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/data:/usr/share/kibana/data
